### ISSUE TITLE
'getUserAPI'  was not found in './actions/course'

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/jupyter-quest#20]
I initially got 'Unexpected token' error from `src/actions/course.js`. 

![screenshot-2018-2-12 react app 1](https://user-images.githubusercontent.com/20701981/36085719-db519366-1002-11e8-9e51-90bf6ea0b332.png)

I then changed `src/actions/course.js` to this:
```javascript
import {Course_Join} from '../app-constant';
const joinCourse = (password) => {
    return {
        type: Course_Join,
        payload:password
       }
    }
export default joinCourse;
```

But then I get this error from `src/rootSaga.js`
![screenshot-2018-2-12 react app](https://user-images.githubusercontent.com/20701981/36085631-0eaadbb0-1002-11e8-8bf1-5e594deb1a57.png)

**Comment by walkwel** [comment]
Rootsaga.js file is no more in use.

**Comment by walkwel** [comment]
You probably have old code. Please have a look at attached screenshot.

![screen shot 2018-02-12 at 12 49 22 pm](https://user-images.githubusercontent.com/23698860/36086589-4e694322-0ff3-11e8-9797-4617bc2ea5e6.png)
