### ISSUE TITLE
Feedback once notebook has been uploaded

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/jupyter-quest#28]
Unable to upload notebook (I am uploading it as a json). 
No feedback about whether notebook was successfully loaded or not. 

![screenshot-2018-2-23 react app](https://user-images.githubusercontent.com/20701981/36577321-a00fd3de-1891-11e8-9b49-3d7330317ad7.png)

Not getting logged within the firebase project. 

![screenshot-2018-2-23 jupyter-dev database firebase console](https://user-images.githubusercontent.com/20701981/36577318-98b0cd6e-1891-11e8-96c1-d796d32eb699.png)

**Comment by walkwel** [comment]
upload button is removed from this page.
instructor upload a file when create a problem in path 
& during creation of  assignment instructor select a path &  problem.
like 
![assignment-form](https://user-images.githubusercontent.com/23698860/36599756-67ce6bb2-18d6-11e8-951d-0ce8eaf03b53.png)

**Comment by anirudhvenu** [comment]
There is no feedback when the notebook has been uploaded. 

![screenshot-2018-2-26 react app 6](https://user-images.githubusercontent.com/20701981/36659287-ef429d72-1b0e-11e8-8e24-ceaa64d523a3.png)
