### ISSUE TITLE
Toggle Feature Not Working

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/jupyter-quest#29]
Even though the toggle for the question is off, the question is displayed. 
![screenshot-2018-2-23 react app 2](https://user-images.githubusercontent.com/20701981/36577501-9ce6ef70-1892-11e8-9c61-af9dd24d84e9.png)
![screenshot-2018-2-23 react app 1](https://user-images.githubusercontent.com/20701981/36577503-9d413570-1892-11e8-99b7-643e577c82df.png)

**Comment by walkwel** [comment]
I implemented functionality like -
if instructor is logged in then he/she can see all the assignments.
if member is logged in then he/she can see only assignments having assignmentVisibility=true

**Comment by anirudhvenu** [comment]
The instructor should be able to see all assignments and solutions in the 'instructor view' tab. 
The 'assignment' tab should contain what the student would see, which is whatever assignments the teacher has decided to make visible.
