### ISSUE TITLE
Unable to View Notebook 

### ISSUE THREAD

**Issue by anirudhvenu** [NUS-ALSET/jupyter-quest#30]
Unable to view the Jupyter notebook after adding an assignment. 

![screenshot-2018-2-23 react app 2](https://user-images.githubusercontent.com/20701981/36577513-b38fa794-1892-11e8-8cf4-3e67403ee971.png)

**Comment by anirudhvenu** [comment]
I have created a notebook and added it to a path. After that I have added it to my course as the instructor. 


![screenshot-2018-2-26 react app 4](https://user-images.githubusercontent.com/20701981/36658839-45c09d2c-1b0d-11e8-88eb-67fa2026280e.png)

When I try to view the notebook as a student the following error occurs. 
![screenshot-2018-2-26 react app 3](https://user-images.githubusercontent.com/20701981/36658862-56a57d60-1b0d-11e8-96ba-b65d52ed0fe8.png)

Also, as the instructor there is no method for viewing the uploaded notebook.  
Please let me know if i'm missing something.

**Comment by walkwel** [comment]
I have used https://github.com/eoinmurray/react-jupyter repo for rendering Jupyter Notebooks. Which required some default key value pair in the json file. Kindly refer to the below code.

```
{
	"cells": [{
		"cell_type": "code",
		"execution_count": 1,
		"metadata": {
			"collapsed": false,
			"deletable": true,
			"editable": true
		},
		"outputs": [{
			"name": "stdout",
			"output_type": "stream",
			"text": [
				"Populating the interactive namespace from numpy and matplotlib\n"
			]
		}],
		"source": [
			"%pylab inline\n",
			"import requests\n",
			"import pandas\n",
			"import json\n",
			"%config InlineBackend.figure_format = 'retina'"
		]
	}],
	"metadata": {
		"kernelspec": {
			"display_name": "Python 3",
			"language": "python",
			"name": "python3"
		},
		"language_info": {
			"codemirror_mode": {
				"name": "ipython",
				"version": 3
			},
			"file_extension": ".py",
			"mimetype": "text/x-python",
			"name": "python",
			"nbconvert_exporter": "python",
			"pygments_lexer": "ipython3",
			"version": "3.5.2"
		}
	},
	"nbformat": 4,
	"nbformat_minor": 2
}
```

**Comment by anirudhvenu** [comment]
The render works for this example file you have shown.
However the component itself can render the json file that threw the previous error I had raised as can be seen here (https://codesandbox.io/s/139mzx8mn4)

However the same notebook is throwing an error when I try to view it as a student in the app itself. 

![screenshot-2018-2-27 react app 7](https://user-images.githubusercontent.com/20701981/36715658-c551501e-1b5c-11e8-84d5-82cb72c38bec.png)
